<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="D:\Hackathon\hackathon\AutomationTestCoverageTool\Customer.Web.Api.AcceptanceTests\bin\Debug\Customer.Web.Api.AcceptanceTests.dll" total="5" errors="5" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2017-11-29" time="13:48:56">
  <environment nunit-version="2.6.0.12051" clr-version="2.0.50727.8762" os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="D:\Hackathon\hackathon\AutomationTestCoverageTool\Customer.Web.Api.AcceptanceTests\bin\Debug" machine-name="ASPUN-WD-VW225" user="Aditi.Kulkarni" user-domain="ASSEENONSCREEN" />
  <culture-info current-culture="en-GB" current-uiculture="en-US" />
  <test-suite type="Test Project" name="" executed="True" result="Failure" success="False" time="9.147" asserts="0">
    <results>
      <test-suite type="Assembly" name="D:\Hackathon\hackathon\AutomationTestCoverageTool\Customer.Web.Api.AcceptanceTests\bin\Debug\Customer.Web.Api.AcceptanceTests.dll" executed="True" result="Failure" success="False" time="5.278" asserts="0">
        <results>
          <test-suite type="Namespace" name="Customer" executed="True" result="Failure" success="False" time="5.261" asserts="0">
            <results>
              <test-suite type="Namespace" name="Web" executed="True" result="Failure" success="False" time="5.260" asserts="0">
                <results>
                  <test-suite type="Namespace" name="Api" executed="True" result="Failure" success="False" time="5.258" asserts="0">
                    <results>
                      <test-suite type="Namespace" name="AcceptanceTests" executed="True" result="Failure" success="False" time="5.258" asserts="0">
                        <results>
                          <test-suite type="Namespace" name="Features" executed="True" result="Failure" success="False" time="5.257" asserts="0">
                            <results>
                              <test-suite type="TestFixture" name="CoverageFeatureFeature" executed="True" result="Failure" success="False" time="4.637" asserts="0">
                                <results>
                                  <test-case name="Customer.Web.Api.AcceptanceTests.Features.CoverageFeatureFeature.PassingValidCustomerDetailsToWebAPI" executed="True" result="Error" success="False" time="3.649" asserts="0">
                                    <categories>
                                      <category name="mytag" />
                                    </categories>
                                    <failure>
                                      <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                                      <stack-trace><![CDATA[at Customer.Web.Api.AcceptanceTests.InsertCustomerSteps.ThenCustomerBlobShouldBeCreated(Table table) in D:\Hackathon\megha\AutomationTestCoverageTool\Customer.Web.Api.AcceptanceTests\InsertCustomerSteps.cs:line 49
at lambda_method(Closure , IContextManager , Table )
at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
at Customer.Web.Api.AcceptanceTests.Features.CoverageFeatureFeature.ScenarioCleanup()
at Customer.Web.Api.AcceptanceTests.Features.CoverageFeatureFeature.PassingValidCustomerDetailsToWebAPI() in D:\Hackathon\megha\AutomationTestCoverageTool\Customer.Web.Api.AcceptanceTests\Features\CoverageFeature.feature:line 11
]]></stack-trace>
                                    </failure>
                                  </test-case>
                                </results>
                              </test-suite>
                              <test-suite type="TestFixture" name="InsertCustomerFeature" executed="True" result="Failure" success="False" time="0.427" asserts="0">
                                <results>
                                  <test-case name="Customer.Web.Api.AcceptanceTests.Features.InsertCustomerFeature.PassingValidCustomerDetailsToWebAPI" executed="True" result="Error" success="False" time="0.420" asserts="0">
                                    <categories>
                                      <category name="mytag" />
                                    </categories>
                                    <failure>
                                      <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                                      <stack-trace><![CDATA[at Customer.Web.Api.AcceptanceTests.InsertCustomerSteps.ThenCustomerBlobShouldBeCreated(Table table) in D:\Hackathon\megha\AutomationTestCoverageTool\Customer.Web.Api.AcceptanceTests\InsertCustomerSteps.cs:line 49
at lambda_method(Closure , IContextManager , Table )
at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
at Customer.Web.Api.AcceptanceTests.Features.InsertCustomerFeature.ScenarioCleanup()
at Customer.Web.Api.AcceptanceTests.Features.InsertCustomerFeature.PassingValidCustomerDetailsToWebAPI() in D:\Hackathon\megha\AutomationTestCoverageTool\Customer.Web.Api.AcceptanceTests\Features\SpecFlowFeature1.feature:line 14
]]></stack-trace>
                                    </failure>
                                  </test-case>
                                </results>
                              </test-suite>
                            </results>
                          </test-suite>
                        </results>
                      </test-suite>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
      <test-suite type="Assembly" name="D:\Hackathon\hackathon\AutomationTestCoverageTool\Customer.Web.Api.AcceptanceTests\bin\Debug\Customer.Web.Api.UnitTests.dll" executed="True" result="Failure" success="False" time="3.627" asserts="0">
        <results>
          <test-suite type="Namespace" name="Customer" executed="True" result="Failure" success="False" time="3.613" asserts="0">
            <results>
              <test-suite type="Namespace" name="Web" executed="True" result="Failure" success="False" time="3.612" asserts="0">
                <results>
                  <test-suite type="Namespace" name="Api" executed="True" result="Failure" success="False" time="3.611" asserts="0">
                    <results>
                      <test-suite type="Namespace" name="UnitTests" executed="True" result="Failure" success="False" time="3.610" asserts="0">
                        <results>
                          <test-suite type="TestFixture" name="CustomerProcessorTests" executed="True" result="Failure" success="False" time="3.609" asserts="0">
                            <results>
                              <test-case name="Customer.Web.Api.UnitTests.CustomerProcessorTests.Return_BlobPath_When_Customer_Is_valid" executed="True" result="Error" success="False" time="3.301" asserts="0">
                                <failure>
                                  <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                                  <stack-trace><![CDATA[at Customer.Web.Api.UnitTests.CustomerProcessorTests.Return_BlobPath_When_Customer_Is_valid() in D:\Hackathon\megha\AutomationTestCoverageTool\Customer.Web.Api.UnitTests\CustomerProcessorTests.cs:line 57
]]></stack-trace>
                                </failure>
                              </test-case>
                              <test-suite type="ParameterizedTest" name="Return_Null_When_Customer_Is_Invalid" executed="True" result="Failure" success="False" time="0.290" asserts="0">
                                <results>
                                  <test-case name="Customer.Web.Api.UnitTests.CustomerProcessorTests.Return_Null_When_Customer_Is_Invalid(0,&quot;Aditi&quot;)" executed="True" result="Error" success="False" time="0.150" asserts="0">
                                    <failure>
                                      <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                                      <stack-trace><![CDATA[at Customer.Web.Api.UnitTests.CustomerProcessorTests.Return_Null_When_Customer_Is_Invalid(Int32 id, String name) in D:\Hackathon\megha\AutomationTestCoverageTool\Customer.Web.Api.UnitTests\CustomerProcessorTests.cs:line 41
]]></stack-trace>
                                    </failure>
                                  </test-case>
                                  <test-case name="Customer.Web.Api.UnitTests.CustomerProcessorTests.Return_Null_When_Customer_Is_Invalid(1,&quot; &quot;)" executed="True" result="Error" success="False" time="0.135" asserts="0">
                                    <failure>
                                      <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
                                      <stack-trace><![CDATA[at Customer.Web.Api.UnitTests.CustomerProcessorTests.Return_Null_When_Customer_Is_Invalid(Int32 id, String name) in D:\Hackathon\megha\AutomationTestCoverageTool\Customer.Web.Api.UnitTests\CustomerProcessorTests.cs:line 41
]]></stack-trace>
                                    </failure>
                                  </test-case>
                                </results>
                              </test-suite>
                            </results>
                          </test-suite>
                        </results>
                      </test-suite>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>